pipeline:
  build:
    image: python:${PYTHON_VERSION}
    commands:
      - wget -O /usr/lib/libmfutil.so http://metwork-framework.org/pub/misc/mfutil_c/libmfutil.so
      - wget -O /usr/lib/liblayerapi2.so http://metwork-framework.org/pub/misc/mfutil_c/liblayerapi2.so
      - ldd /usr/lib/libmfutil.so
      - ldd /usr/lib/liblayerapi2.so
      - mkdir -p /opt/metwork-mfext/lib
      - pip install -r dev-requirements.txt
      - python setup.py develop
      - cd tests && rm -f test_plugins.py && nosetests -s . && cd ..
      - flake8 .
      - if test "${PYTHON_VERSION}" != "3.7-buster"; then exit 0; fi
      - pdoc --html mfutil
  publish:
    image: python:${PYTHON_VERSION}
    volumes:
      - /pub:/pub
    commands:
      - env |grep DRONE_BRANCH
      - echo ${DRONE_BRANCH}
      - if test "${PYTHON_VERSION}" != "3.7-buster"; then exit 0; fi
      - rm -Rf /pub/misc/mfutil/doc
      - mkdir -p /pub/misc/mfutil/doc/${DRONE_BRANCH}
      - cp -Rf html/mfutil/* /pub/misc/mfutil/doc/${DRONE_BRANCH}/
    when:
      event: push

matrix:
  PYTHON_VERSION:
    - 3.7-buster
